name: EDA
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python -m src.eda
          git fetch --prune
          # dvc metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## EDA"
          cml-publish ./AutoViz_Plots/Converted/Dist_Plots_target.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Bar_Plots.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Dist_Plots_Numerics.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Scatter_Plots.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Box_Plots.png --md >> report.md

          cml-send-comment report.md
