name: EDA
on:
  push:
    branches: ["eda"]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -q pandas xlrd autoviz
          # https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time/14132912#14132912
          python -m src.eda
          git fetch --prune
          # dvc metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## EDA" > report.md
          cml-publish ./AutoViz_Plots/Converted/Dist_Plots_target.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Bar_Plots.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Dist_Plots_Numerics.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Scatter_Plots.png --md >> report.md
          cml-publish ./AutoViz_Plots/Converted/Box_Plots.png --md >> report.md

          cml-send-comment report.md
